version: '3.8'

services:
  maps-business-finder:
    build: .
    container_name: maps-business-finder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - BROWSER_HEADLESS=true
      - BROWSER_TIMEOUT=30000
    volumes:
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./exports:/app/exports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  maps-business-finder-dev:
    build: .
    container_name: maps-business-finder-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=debug
      - BROWSER_HEADLESS=false
      - BROWSER_TIMEOUT=60000
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./exports:/app/exports
    command: npm run dev
    profiles:
      - dev

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: maps-business-finder-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - maps-business-finder
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: maps-business-finder-network 